In [18]:
## Predicitng Models


from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\PNEUMONIA\\person1946_bacteria_4874.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [19]:
classes

array([[0., 1.]], dtype=float32)

In [20]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\NORMAL\\NORMAL2-IM-1427-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [21]:
classes

array([[6.17837e-11, 1.00000e+00]], dtype=float32)

In [22]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\NORMAL\\NORMAL2-IM-1436-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [23]:
classes

array([[9.999999e-01, 1.579374e-07]], dtype=float32)

In [24]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\NORMAL\\NORMAL2-IM-1431-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [25]:
classes

array([[0.0285759 , 0.97142404]], dtype=float32)

In [26]:


from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\PNEUMONIA\\person1949_bacteria_4880.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [27]:
classes

array([[0., 1.]], dtype=float32)

In [28]:

from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\chest_xray\\val\\PNEUMONIA\\person1950_bacteria_4881.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [29]:
classes

array([[0., 1.]], dtype=float32)

In [30]:

from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\chest_xray\\val\\PNEUMONIA\\person1954_bacteria_4886.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [31]:
classes

array([[8.226901e-17, 1.000000e+00]], dtype=float32)

In [32]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\NORMAL\\NORMAL2-IM-1440-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [33]:
classes

array([[0., 1.]], dtype=float32)

In [36]:

from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\chest_xray\\val\\NORMAL\\NORMAL2-IM-1438-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [37]:
classes

array([[0., 1.]], dtype=float32)

In [40]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\PNEUMONIA\\person1952_bacteria_4883.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [41]:
classes

array([[0., 1.]], dtype=float32)

In [42]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
model = load_model('model_vgg19.h5')
img = image.load_img('D:\\Projects_ml\\chest_xray\\val\\PNEUMONIA\\person1946_bacteria_4875.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
classes = model.predict(img_data)

In [43]:
classes

array([[0., 1.]], dtype=float32)